GET http://localhost:4000/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJUdWFuVHJhbiIsImlhdCI6MTY2ODUzMDM0NX0.CTNeKwYtgZX0FKYFI6pjX6sUzjTgiTMaP7IYfWQBs4o

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "TuanTran"
}

###

POST http://localhost:5000/token 
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJUdWFuVHJhbiIsImlhdCI6MTY2ODUzMDM0NSwiZXhwIjoxNjY4NTMzOTQ1fQ.iu3kSs2o7g4RhzYdWXg6ofvqiWNhBAVXsTIFf3-uB_w"
}

###

POST http://localhost:5000/logout 
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJUdWFuVHJhbiIsImlhdCI6MTY2ODUzMDM0NX0.CTNeKwYtgZX0FKYFI6pjX6sUzjTgiTMaP7IYfWQBs4o

